#!/usr/bin/env python3
"""Regenerates src/LogoData.h from assets/logo.png.

The overlay draws the logo at 40x40. It is stored at exactly twice that, so the GPU's bilinear
filter averages each 2x2 block evenly instead of skipping texels. Requires Pillow:
    pip install pillow
    python tools/embed_logo.py
"""
from pathlib import Path
from PIL import Image

SIZE = 80
root = Path(__file__).resolve().parent.parent
img = Image.open(root / "assets" / "logo.png").convert("RGBA").resize((SIZE, SIZE), Image.LANCZOS)
data = img.tobytes()

lines = []
for i in range(0, len(data), 24):
    lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 24]) + ",")

out = f"""#pragma once

// Generated by tools/embed_logo.py from assets/logo.png. Do not edit by hand.
// {SIZE}x{SIZE}, 8-bit RGBA, straight (not premultiplied) alpha, rows top to bottom.
namespace TextureToolkit
{{
    constexpr unsigned int kLogoSize = {SIZE};
    inline constexpr unsigned char kLogoRGBA[{len(data)}] = {{
{chr(10).join(lines)}
    }};
}}
"""
(root / "src" / "LogoData.h").write_text(out, newline="\n")
print(f"wrote src/LogoData.h ({SIZE}x{SIZE})")
